name: lsh
services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lsh
    environment:
      - JAIL_TIME=60
      - JAIL_CONNS_PER_IP=5
      - JAIL_POW=0
    ports:
      - "5594:5000"
    privileged: true
    restart: always
